# Generated by Django 2.2.2 on 2021-01-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_contact_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_list',
            new_name='ContactList',
        ),
    ]
